[project]
name = "freqtradestudy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "filelock>=3.19.1",
    "freqtrade[hyperopt]>=2025.6",
    "scikit-optimize>=0.10.2",
]
